name: test

on: pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            #----------------------------------------------
            #       check-out repo and set-up python
            #----------------------------------------------
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Set up python
              uses: actions/setup-python@v4
              id: setup-python
              with:
                  python-version: "3.11.2"
            #----------------------------------------------
            #  -----  install & configure poetry  -----
            #----------------------------------------------
            - name: Install Poetry
              uses: dschep/install-poetry-action@v1.2
            - name: Cache Poetry virtualenv
              uses: actions/cache@v1
              id: cache
              with:
                  path: ~/.virtualenvs
                  key: poetry-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: |
                      poetry-${{ hashFiles('**/poetry.lock') }}
            - name: Set Poetry config
              run: |
                  poetry config settings.virtualenvs.in-project false
                  poetry config settings.virtualenvs.path ~/.virtualenvs

            # #----------------------------------------------
            # install your root project, if required
            #----------------------------------------------
            - name: Install Dependencies
              run: poetry install --no-root
              if: steps.cache.outputs.cache-hit != 'true'
            #----------------------------------------------
            #              run test suite
            #----------------------------------------------
            - run: poetry run pre-commit run --all-files
